[build]
  command = "npm run build"
  publish = "build/client"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run dev"
  targetPort = 3000

[functions]
  directory = "build/server"
  node_bundler = "esbuild"

[[plugins]]
  package = "@netlify/plugin-remix"
